name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.11
        uses: actions/setup-node@v4
        with:
          node-version: 20.11
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build -- --configuration=production
      - name: Test
        run: npm test -- --configuration=ci
#      - name: E2E
#        run: npm run e2e -- --configuration=ci
