name: IdleGame-Web CI/CD

on:
  push:
    branches:
      - main
      - release/**
    paths-ignore:
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'README.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'README.md'
      - 'docs/**'

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build -- --configuration=production
      - name: Test
        run: npm test -- --configuration=ci
#      - name: E2E
#        run: npm run e2e -- --configuration=ci
